### ISSUE TITLE
Code review with muh bros

### ISSUE THREAD

**Issue by marthinwurer** [catszeid/ardrone_control#1]
For this code review, remember that we both want your code to get better. This is constructive criticism, and if you disagree with something, then you can explain yourself. Keep a level head and let's `git gud` together.

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L231

Silent failure, log something here

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L94

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L214

Code reuse, make a function to reset the velocities.

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L100

Here, what I'd do is check if the number of hands is zero, and then continue if it is. This keeps the rest of the function at the base level and easier to read. This might not be the correct thing to do, but take a look at it and defend your reason in a comment :)

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L130

Assign the r_roll_offset_left or l_roll_offset_left to a variable in the if block depending on what hand it is, and then use that variable in the following block. This will reduce code reuse. 

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L164

Here too.

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L169

See if you can find some way to not set this every time.

https://github.com/catszeid/ardrone_control/blob/f00e5f8354c42db0cf9f26381800d060e2de6c13/scripts/leap_control.py#L212

Do you need to reset this here? Is moved ever not set if you have moved? You might be able to get rid of this block of code and the moved variable if that's the case.

You've got a good start here, and I'd love to see more of this in action.

**Comment by catszeid** [comment]
> Silent failure, log something here

I have removed the silent failure from my new version of the script.

> Code reuse, make a function to reset the velocities.

I made a function to handle resetting the values of the Twist message.

> Here, what I'd do is check if the number of hands is zero, and then continue if it is. This keeps the rest of the function at the base level and easier to read. This might not be the correct thing to do, but take a look at it and defend your reason in a comment :)

I am not quite sure what you mean by continuing when there are no hands. How I have it right now, I am running the code only if I have a hand in the frame. This makes logical sense to me.

> Assign the r_roll_offset_left or l_roll_offset_left to a variable in the if block depending on what hand it is, and then use that variable in the following block. This will reduce code reuse.

I should be able to do that. That seems like a cleaner execution of what I am trying to do with that code.

> See if you can find some way to not set this every time.

> Do you need to reset this here? Is moved ever not set if you have moved? You might be able to get rid of this block of code and the moved variable if that's the case.

I think that I will be able to get rid of the moved variable by adding a function that tells me if all of the values of the Twist are zero.

Thanks for the code review!

**Comment by marthinwurer** [comment]
https://github.com/catszeid/ardrone_control/blob/9e595829219bcc1d73f6d3624e751a69f0b1c95c/scripts/leap_control.py#L62-L70

can be replaced with returning the result of that large comparison

https://github.com/catszeid/ardrone_control/blob/9e595829219bcc1d73f6d3624e751a69f0b1c95c/scripts/leap_control.py#L85-L105

Is this drone info or is it hand info or is it settings info? If not, then it should be broken up into more modular parts.

https://github.com/catszeid/ardrone_control/blob/9e595829219bcc1d73f6d3624e751a69f0b1c95c/scripts/leap_control.py#L120-L122

Do you need to do anything else to stop input in the out of battery state?

https://github.com/catszeid/ardrone_control/blob/9e595829219bcc1d73f6d3624e751a69f0b1c95c/scripts/leap_control.py#L166-L170

Do you need separate left and right offsets for each hand? Ie, is r_roll_offset_left different from l_roll_offset_right?

Otherwise looks good!

**Comment by catszeid** [comment]
> can be replaced with returning the result of that large comparison

Makes sense, I will change that.

>  Is this drone info or is it hand info or is it settings info? If not, then it should be broken up into more modular parts.

These are the various settings that are used in processing for the drone.

> Do you need to do anything else to stop input in the out of battery state?

I will add code to exit the program once the drone is landed.

> Do you need separate left and right offsets for each hand? Ie, is r_roll_offset_left different from l_roll_offset_right?

The left and right hand have a difference in rotation that needs to be tuned in the future.
